services:
  jetstream:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jetstream_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - jetstream_network

  jetstream_nginx:
    image: nginx:alpine
    container_name: jetstream_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - jetstream_network

  jetstream_db:
    image: mysql:8.0
    container_name: jetstream_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jetstream
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: jetstream
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - jetstream_network

networks:
  jetstream_network:
    driver: bridge

volumes:
  db_data: